[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "https://campermateitalia.com/*"
  to = "https://www.campermateitalia.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://campermateitalia.com/*"
  to = "https://www.campermateitalia.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.campermateitalia.com/*"
  to = "https://www.campermateitalia.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/geocode"
  to = "/.netlify/functions/geocode"
  status = 200

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200

[[redirects]]
  from = "/api/admin-users"
  to = "/.netlify/functions/admin-users"
  status = 200

[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200
